// examples/qwikcity/src/routes/index.tsx
import { component$ } from "@builder.io/qwik"
import { Link } from "@builder.io/qwik-city"

export default component$(() => {
	return (
		<>
			<h1>Welcome to QwikCity</h1>
			<p>This is a QwikCity example with Screenbook integration.</p>
			<nav>
				<ul>
					<li>
						<Link href="/about">About</Link>
					</li>
					<li>
						<Link href="/users">Users</Link>
					</li>
				</ul>
			</nav>
		</>
	)
})

// examples/solidstart/src/routes/index.tsx
import { A } from "@solidjs/router"

export default function Home() {
	return (
		<main>
			<h1>Welcome to SolidStart</h1>
			<p>This is a SolidStart example with Screenbook integration.</p>
			<nav>
				<ul>
					<li>
						<A href="/about">About</A>
					</li>
					<li>
						<A href="/users">Users</A>
					</li>
				</ul>
			</nav>
		</main>
	)
}
