// examples/solid-router/src/App.tsx
import { A } from "@solidjs/router"
import type { ParentProps } from "solid-js"

export default function App(props: ParentProps) {
	return (
		<div>
			<nav style={{ padding: "1rem", "border-bottom": "1px solid #ccc" }}>
				<A href="/" style={{ "margin-right": "1rem" }}>
					Home
				</A>
				<A href="/about" style={{ "margin-right": "1rem" }}>
					About
				</A>
				<A href="/dashboard" style={{ "margin-right": "1rem" }}>
					Dashboard
				</A>
				<A href="/user/123">User 123</A>
			</nav>
			<main style={{ padding: "1rem" }}>{props.children}</main>
		</div>
	)
}

// examples/vue-router/src/App.vue
<script setup lang="ts">
import { RouterView, RouterLink } from 'vue-router'
</script>

<template>
  <div>
    <nav>
      <RouterLink to="/">Home</RouterLink> |
      <RouterLink to="/dashboard">Dashboard</RouterLink> |
      <RouterLink to="/settings">Settings</RouterLink> |
      <RouterLink to="/user/1/profile">User Profile</RouterLink>
    </nav>
    <main>
      <RouterView />
    </main>
  </div>
</template>

<style scoped>
nav {
  padding: 1rem;
  background: #f0f0f0;
}
nav a {
  margin: 0 0.5rem;
}
main {
  padding: 1rem;
}
</style>
