// examples/nextjs-app-router/src/app/page.tsx
import Link from "next/link"

export default function Home() {
	return (
		<main style={{ padding: "2rem" }}>
			<h1>Home</h1>
			<p>Welcome to the Next.js App Router example with Screenbook.</p>
			<nav style={{ marginTop: "1rem" }}>
				<ul>
					<li>
						<Link href="/dashboard">Dashboard</Link>
					</li>
					<li>
						<Link href="/settings">Settings</Link>
					</li>
				</ul>
			</nav>
		</main>
	)
}

// examples/vue-router/src/App.vue
<script setup lang="ts">
import { RouterView, RouterLink } from 'vue-router'
</script>

<template>
  <div>
    <nav>
      <RouterLink to="/">Home</RouterLink> |
      <RouterLink to="/dashboard">Dashboard</RouterLink> |
      <RouterLink to="/settings">Settings</RouterLink> |
      <RouterLink to="/user/1/profile">User Profile</RouterLink>
    </nav>
    <main>
      <RouterView />
    </main>
  </div>
</template>

<style scoped>
nav {
  padding: 1rem;
  background: #f0f0f0;
}
nav a {
  margin: 0 0.5rem;
}
main {
  padding: 1rem;
}
</style>
